// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: kv/kv.proto

package kv

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKVRequest) Reset() {
	*x = GetKVRequest{}
	mi := &file_kv_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVRequest) ProtoMessage() {}

func (x *GetKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVRequest.ProtoReflect.Descriptor instead.
func (*GetKVRequest) Descriptor() ([]byte, []int) {
	return file_kv_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode    int64                  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKVResponse) Reset() {
	*x = GetKVResponse{}
	mi := &file_kv_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVResponse) ProtoMessage() {}

func (x *GetKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVResponse.ProtoReflect.Descriptor instead.
func (*GetKVResponse) Descriptor() ([]byte, []int) {
	return file_kv_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetKVResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetKVResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetKVResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetKeyValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyValueRequest) Reset() {
	*x = SetKeyValueRequest{}
	mi := &file_kv_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyValueRequest) ProtoMessage() {}

func (x *SetKeyValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyValueRequest.ProtoReflect.Descriptor instead.
func (*SetKeyValueRequest) Descriptor() ([]byte, []int) {
	return file_kv_kv_proto_rawDescGZIP(), []int{2}
}

func (x *SetKeyValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetKeyValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetKeyValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode    int64                  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeyValueResponse) Reset() {
	*x = SetKeyValueResponse{}
	mi := &file_kv_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeyValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyValueResponse) ProtoMessage() {}

func (x *SetKeyValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyValueResponse.ProtoReflect.Descriptor instead.
func (*SetKeyValueResponse) Descriptor() ([]byte, []int) {
	return file_kv_kv_proto_rawDescGZIP(), []int{3}
}

func (x *SetKeyValueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetKeyValueResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_kv_kv_proto protoreflect.FileDescriptor

const file_kv_kv_proto_rawDesc = "" +
	"\n" +
	"\vkv/kv.proto\x12\x02kv\x1a\x1cgoogle/api/annotations.proto\" \n" +
	"\fGetKVRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"_\n" +
	"\rGetKVResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\x03R\n" +
	"statusCode\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"<\n" +
	"\x12SetKeyValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"O\n" +
	"\x13SetKeyValueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\x03R\n" +
	"statusCode2\x80\x02\n" +
	"\rKeyValueStore\x12I\n" +
	"\vGetKeyValue\x12\x10.kv.GetKVRequest\x1a\x11.kv.GetKVResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/kv/{key}\x12R\n" +
	"\vSetKeyValue\x12\x16.kv.SetKeyValueRequest\x1a\x17.kv.SetKeyValueResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/api/kv\x12P\n" +
	"\x0eDeleteKeyValue\x12\x10.kv.GetKVRequest\x1a\x11.kv.GetKVResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/kv/deleteB\fZ\n" +
	"./proto/kvb\x06proto3"

var (
	file_kv_kv_proto_rawDescOnce sync.Once
	file_kv_kv_proto_rawDescData []byte
)

func file_kv_kv_proto_rawDescGZIP() []byte {
	file_kv_kv_proto_rawDescOnce.Do(func() {
		file_kv_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_kv_proto_rawDesc), len(file_kv_kv_proto_rawDesc)))
	})
	return file_kv_kv_proto_rawDescData
}

var file_kv_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kv_kv_proto_goTypes = []any{
	(*GetKVRequest)(nil),        // 0: kv.GetKVRequest
	(*GetKVResponse)(nil),       // 1: kv.GetKVResponse
	(*SetKeyValueRequest)(nil),  // 2: kv.SetKeyValueRequest
	(*SetKeyValueResponse)(nil), // 3: kv.SetKeyValueResponse
}
var file_kv_kv_proto_depIdxs = []int32{
	0, // 0: kv.KeyValueStore.GetKeyValue:input_type -> kv.GetKVRequest
	2, // 1: kv.KeyValueStore.SetKeyValue:input_type -> kv.SetKeyValueRequest
	0, // 2: kv.KeyValueStore.DeleteKeyValue:input_type -> kv.GetKVRequest
	1, // 3: kv.KeyValueStore.GetKeyValue:output_type -> kv.GetKVResponse
	3, // 4: kv.KeyValueStore.SetKeyValue:output_type -> kv.SetKeyValueResponse
	1, // 5: kv.KeyValueStore.DeleteKeyValue:output_type -> kv.GetKVResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kv_kv_proto_init() }
func file_kv_kv_proto_init() {
	if File_kv_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_kv_proto_rawDesc), len(file_kv_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_kv_proto_goTypes,
		DependencyIndexes: file_kv_kv_proto_depIdxs,
		MessageInfos:      file_kv_kv_proto_msgTypes,
	}.Build()
	File_kv_kv_proto = out.File
	file_kv_kv_proto_goTypes = nil
	file_kv_kv_proto_depIdxs = nil
}
